VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # config.vm.define "zk2" do |zk_config|
  #   zk_config.vm.box = "hashicorp/precise64"
  #   zk_config.vm.network "private_network", :ip => "192.168.12.12"
  #   zk_config.vm.provision :shell, :path => "vm-zookeeper.sh", :args => 2
  # end

  ["1", "2", "3"].each do |n|
    config.vm.define "zk#{n}" do |zk_config|
      zk_config.vm.box = "hashicorp/precise64"
      zk_config.vm.network "private_network", :ip => "192.168.12.1#{n}"
      zk_config.vm.provision :shell, :path => "vm-zookeeper.sh", :args => n
    end
  end

  config.vm.define "go" do |go_config|
    go_config.vm.box = "hashicorp/precise64"
    go_config.vm.network "private_network", :ip => "129.168.12.10"
    go_config.vm.provision :shell, :path => "vm-go.sh"
    #映射主机目录到虚拟机(主机根目录是运行vagrant时的当前目录，默认它将映射到/vagrant目录)
    #go_config.vm.synced_folder "work-dir/", "/var/www"
  end
end
